name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: clean
        run: cargo +nightly clean
      - name: build
        run: cargo +nightly build --jobs=1
      - name: fmt
        run: cargo +nightly fmt
      - name: fix
        run: cargo +nightly fix --all-features --allow-dirty --allow-staged --jobs=1
      - name: test
        run: cargo +nightly test --all-features --verbose -- --test-threads=1
      - name: clippy
        run: cargo +nightly clippy --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean
        run: cargo +nightly clean
      - name: build
        run: cargo +nightly build --jobs=1
      - name: clippy
        run: cargo +nightly clippy -- -D warnings
